# Generated by Django 3.0.3 on 2020-04-20 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mainapp.BudgetCategory'),
        ),
        migrations.AlterField(
            model_name='budgetsetup',
            name='mybuget',
            field=models.FloatField(default=2000),
        ),
    ]
