# Generated by Django 3.0.3 on 2020-04-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200420_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addexpense',
            name='budget_set',
        ),
        migrations.DeleteModel(
            name='BudgetSetup',
        ),
    ]
