# Generated by Django 3.0.3 on 2020-04-24 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200420_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addexpense',
            name='auto_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='addexpense',
            name='entered_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
