# Generated by Django 3.0.3 on 2020-04-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Address',
            field=models.TextField(default='notgiven', max_length=120),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='notgiven', max_length=120),
        ),
        migrations.AlterField(
            model_name='users',
            name='is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
