# Generated by Django 3.0.3 on 2020-04-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200425_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='Address',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
